"""schema tardanzas modulo v1

Revision ID: 1d60112021c7
Revises: df83e5d14dd3
Create Date: 2026-09-04 09:12:51.874064
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d60112021c7'
down_revision: str | None = 'df83e5d14dd3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_settings'))
    )
    op.create_index(op.f('ix_app_settings_key'), 'app_settings', ['key'], unique=True)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments'))
    )
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_table('processing_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_file_name', sa.String(length=500), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('total_entries', sa.Integer(), nullable=False),
    sa.Column('total_exits', sa.Integer(), nullable=False),
    sa.Column('total_late_arrivals', sa.Integer(), nullable=False),
    sa.Column('total_without_late', sa.Integer(), nullable=False),
    sa.Column('total_inconsistencies', sa.Integer(), nullable=False),
    sa.Column('total_early_leaves', sa.Integer(), nullable=False),
    sa.Column('total_record_count_issues', sa.Integer(), nullable=False),
    sa.Column('report_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_history'))
    )
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processing_history_id', sa.Integer(), nullable=False),
    sa.Column('legajo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('department_name', sa.String(length=200), nullable=False),
    sa.Column('record_type', sa.String(length=20), nullable=False),
    sa.Column('record_date', sa.DateTime(), nullable=False),
    sa.Column('record_datetime', sa.DateTime(), nullable=False),
    sa.Column('day_of_week', sa.String(length=20), nullable=True),
    sa.Column('classification', sa.String(length=200), nullable=False),
    sa.Column('late_minutes', sa.Integer(), nullable=False),
    sa.Column('early_leave_minutes', sa.Integer(), nullable=False),
    sa.Column('is_inconsistency', sa.Boolean(), nullable=False),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['processing_history_id'], ['processing_history.id'], name=op.f('fk_attendance_records_processing_history_id_processing_history'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_records'))
    )
    op.create_index(op.f('ix_attendance_records_department_id'), 'attendance_records', ['department_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_department_name'), 'attendance_records', ['department_name'], unique=False)
    op.create_index(op.f('ix_attendance_records_legajo'), 'attendance_records', ['legajo'], unique=False)
    op.create_index(op.f('ix_attendance_records_processing_history_id'), 'attendance_records', ['processing_history_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_record_date'), 'attendance_records', ['record_date'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('days_of_week', sa.Text(), nullable=False),
    sa.Column('tolerance_min', sa.Integer(), nullable=False),
    sa.Column('expected_entries_per_day', sa.Integer(), nullable=True),
    sa.Column('expected_exits_per_day', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_schedules_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedules'))
    )
    op.create_index(op.f('ix_schedules_department_id'), 'schedules', ['department_id'], unique=False)
    op.create_table('schedule_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('start_time', sa.String(length=8), nullable=False),
    sa.Column('end_time', sa.String(length=8), nullable=False),
    sa.Column('block_order', sa.Integer(), nullable=False),
    sa.Column('crosses_midnight', sa.Boolean(), nullable=False),
    sa.Column('is_entry_point', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name=op.f('fk_schedule_blocks_schedule_id_schedules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_blocks'))
    )
    op.create_index(op.f('ix_schedule_blocks_schedule_id'), 'schedule_blocks', ['schedule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_blocks_schedule_id'), table_name='schedule_blocks')
    op.drop_table('schedule_blocks')
    op.drop_index(op.f('ix_schedules_department_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_attendance_records_record_date'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_processing_history_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_legajo'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_department_name'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_department_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_table('processing_history')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_app_settings_key'), table_name='app_settings')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
