"""foto de equipo

Revision ID: 1e89e68f7c20
Revises: 7db8918ddf5f
Create Date: 2026-09-03 07:39:17.100763
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e89e68f7c20'
down_revision: str | None = '7db8918ddf5f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipos', sa.Column('foto_mime', sa.String(length=50), nullable=True))
    op.add_column('equipos', sa.Column('foto', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipos', 'foto')
    op.drop_column('equipos', 'foto_mime')
    # ### end Alembic commands ###
