"""usuario es_protegido

Revision ID: 3c48a1bee3a6
Revises: 860808e98b79
Create Date: 2026-08-31 10:38:54.211300
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c48a1bee3a6'
down_revision: str | None = '860808e98b79'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # server_default para poblar las filas existentes; luego se retira el default
    # a nivel de esquema (el valor por defecto lo maneja el modelo/ORM).
    op.add_column(
        "usuarios",
        sa.Column(
            "es_protegido",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.alter_column("usuarios", "es_protegido", server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'es_protegido')
    # ### end Alembic commands ###
