"""inventario ampliado 68 campos

Revision ID: 7db8918ddf5f
Revises: a6e34c01cd0f
Create Date: 2026-09-01 16:13:37.983187
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7db8918ddf5f'
down_revision: str | None = 'a6e34c01cd0f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Nuevo valor 'NR' (no reglamentado) para la clasificación de riesgo.
    op.execute("ALTER TYPE clasificacion_riesgo ADD VALUE IF NOT EXISTS 'NR'")
    op.add_column('equipos', sa.Column('numero_activo', sa.String(length=50), nullable=True))
    op.add_column('equipos', sa.Column('piso', sa.String(length=50), nullable=True))
    op.add_column('equipos', sa.Column('clase_biomedica', sa.String(length=60), nullable=True))
    op.add_column('equipos', sa.Column('clase_uso', sa.String(length=40), nullable=True))
    op.add_column('equipos', sa.Column('tecnologia_predominante', sa.String(length=40), nullable=True))
    op.add_column('equipos', sa.Column('fabricante', sa.String(length=150), nullable=True))
    op.add_column('equipos', sa.Column('anio_fabricacion', sa.Integer(), nullable=True))
    op.add_column('equipos', sa.Column('pais_fabricante', sa.String(length=100), nullable=True))
    op.add_column('equipos', sa.Column('ciudad_fabricante', sa.String(length=100), nullable=True))
    op.add_column('equipos', sa.Column('direccion_fabricante', sa.String(length=200), nullable=True))
    op.add_column('equipos', sa.Column('telefono_fabricante', sa.String(length=50), nullable=True))
    op.add_column('equipos', sa.Column('correo_fabricante', sa.String(length=150), nullable=True))
    op.add_column('equipos', sa.Column('representante', sa.String(length=150), nullable=True))
    op.add_column('equipos', sa.Column('pais_representante', sa.String(length=100), nullable=True))
    op.add_column('equipos', sa.Column('ciudad_representante', sa.String(length=100), nullable=True))
    op.add_column('equipos', sa.Column('direccion_representante', sa.String(length=200), nullable=True))
    op.add_column('equipos', sa.Column('telefono_representante', sa.String(length=50), nullable=True))
    op.add_column('equipos', sa.Column('correo_representante', sa.String(length=150), nullable=True))
    op.add_column('equipos', sa.Column('voltaje_operacion', sa.String(length=50), nullable=True))
    op.add_column('equipos', sa.Column('voltaje_maximo', sa.String(length=50), nullable=True))
    op.add_column('equipos', sa.Column('corriente_maxima', sa.String(length=50), nullable=True))
    op.add_column('equipos', sa.Column('corriente_minima', sa.String(length=50), nullable=True))
    op.add_column('equipos', sa.Column('potencia_consumida', sa.String(length=50), nullable=True))
    op.add_column('equipos', sa.Column('frecuencia', sa.String(length=50), nullable=True))
    op.add_column('equipos', sa.Column('presion', sa.String(length=50), nullable=True))
    op.add_column('equipos', sa.Column('velocidad', sa.String(length=50), nullable=True))
    op.add_column('equipos', sa.Column('temperatura', sa.String(length=50), nullable=True))
    op.add_column('equipos', sa.Column('peso', sa.String(length=50), nullable=True))
    op.add_column('equipos', sa.Column('capacidad', sa.String(length=50), nullable=True))
    op.add_column('equipos', sa.Column('fuentes_alimentacion', postgresql.ARRAY(sa.String(length=40)), nullable=True))
    op.add_column('equipos', sa.Column('manuales', postgresql.ARRAY(sa.String(length=40)), nullable=True))
    op.add_column('equipos', sa.Column('planos', postgresql.ARRAY(sa.String(length=40)), nullable=True))
    op.add_column('equipos', sa.Column('recomendaciones_fabricante', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('equipos', sa.Column('modo_adquisicion', sa.String(length=40), nullable=True))
    op.add_column('equipos', sa.Column('fecha_inicial_garantia', sa.Date(), nullable=True))
    op.add_column('equipos', sa.Column('fecha_final_garantia', sa.Date(), nullable=True))
    op.add_column('equipos', sa.Column('fecha_instalacion', sa.Date(), nullable=True))
    op.add_column('equipos', sa.Column('fecha_funcionamiento', sa.Date(), nullable=True))
    op.add_column('equipos', sa.Column('fecha_vencimiento_invima', sa.Date(), nullable=True))
    op.add_column('equipos', sa.Column('periodicidad_mantenimiento', sa.String(length=100), nullable=True))
    op.add_column('equipos', sa.Column('calibracion_si', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('equipos', sa.Column('calibracion_no', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('equipos', sa.Column('equipo_movil', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('equipos', sa.Column('equipo_fijo', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('equipos', sa.Column('accesorios', sa.Text(), nullable=True))
    op.add_column('equipos', sa.Column('descripcion_funcional', sa.Text(), nullable=True))
    op.create_index(op.f('ix_equipos_numero_activo'), 'equipos', ['numero_activo'], unique=False)
    op.drop_column('equipos', 'fin_garantia')
    op.drop_column('equipos', 'criticidad')
    # El tipo enum 'criticidad' queda huérfano tras eliminar la columna.
    op.execute("DROP TYPE IF EXISTS criticidad")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipos', sa.Column('criticidad', postgresql.ENUM('alta', 'media', 'baja', name='criticidad'), autoincrement=False, nullable=True))
    op.add_column('equipos', sa.Column('fin_garantia', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_equipos_numero_activo'), table_name='equipos')
    op.drop_column('equipos', 'descripcion_funcional')
    op.drop_column('equipos', 'accesorios')
    op.drop_column('equipos', 'equipo_fijo')
    op.drop_column('equipos', 'equipo_movil')
    op.drop_column('equipos', 'calibracion_no')
    op.drop_column('equipos', 'calibracion_si')
    op.drop_column('equipos', 'periodicidad_mantenimiento')
    op.drop_column('equipos', 'fecha_vencimiento_invima')
    op.drop_column('equipos', 'fecha_funcionamiento')
    op.drop_column('equipos', 'fecha_instalacion')
    op.drop_column('equipos', 'fecha_final_garantia')
    op.drop_column('equipos', 'fecha_inicial_garantia')
    op.drop_column('equipos', 'modo_adquisicion')
    op.drop_column('equipos', 'recomendaciones_fabricante')
    op.drop_column('equipos', 'planos')
    op.drop_column('equipos', 'manuales')
    op.drop_column('equipos', 'fuentes_alimentacion')
    op.drop_column('equipos', 'capacidad')
    op.drop_column('equipos', 'peso')
    op.drop_column('equipos', 'temperatura')
    op.drop_column('equipos', 'velocidad')
    op.drop_column('equipos', 'presion')
    op.drop_column('equipos', 'frecuencia')
    op.drop_column('equipos', 'potencia_consumida')
    op.drop_column('equipos', 'corriente_minima')
    op.drop_column('equipos', 'corriente_maxima')
    op.drop_column('equipos', 'voltaje_maximo')
    op.drop_column('equipos', 'voltaje_operacion')
    op.drop_column('equipos', 'correo_representante')
    op.drop_column('equipos', 'telefono_representante')
    op.drop_column('equipos', 'direccion_representante')
    op.drop_column('equipos', 'ciudad_representante')
    op.drop_column('equipos', 'pais_representante')
    op.drop_column('equipos', 'representante')
    op.drop_column('equipos', 'correo_fabricante')
    op.drop_column('equipos', 'telefono_fabricante')
    op.drop_column('equipos', 'direccion_fabricante')
    op.drop_column('equipos', 'ciudad_fabricante')
    op.drop_column('equipos', 'pais_fabricante')
    op.drop_column('equipos', 'anio_fabricacion')
    op.drop_column('equipos', 'fabricante')
    op.drop_column('equipos', 'tecnologia_predominante')
    op.drop_column('equipos', 'clase_uso')
    op.drop_column('equipos', 'clase_biomedica')
    op.drop_column('equipos', 'piso')
    op.drop_column('equipos', 'numero_activo')
    # ### end Alembic commands ###
