"""esquema inicial inventario

Revision ID: 918322214cfe
Revises: 
Create Date: 2026-08-31 09:13:17.204311
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '918322214cfe'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('nit', sa.String(length=30), nullable=True),
    sa.Column('contacto', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proveedores'))
    )
    op.create_index(op.f('ix_proveedores_nombre'), 'proveedores', ['nombre'], unique=True)
    op.create_table('sedes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('direccion', sa.String(length=250), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sedes'))
    )
    op.create_index(op.f('ix_sedes_nombre'), 'sedes', ['nombre'], unique=True)
    op.create_table('servicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], name=op.f('fk_servicios_sede_id_sedes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_servicios'))
    )
    op.create_index(op.f('ix_servicios_nombre'), 'servicios', ['nombre'], unique=False)
    op.create_index(op.f('ix_servicios_sede_id'), 'servicios', ['sede_id'], unique=False)
    op.create_table('equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_interno', sa.String(length=50), nullable=False),
    sa.Column('serial_fabricante', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('criticidad', sa.Enum('alta', 'media', 'baja', name='criticidad'), nullable=True),
    sa.Column('registro_invima', sa.String(length=100), nullable=True),
    sa.Column('clasificacion_riesgo', sa.Enum('I', 'IIa', 'IIb', 'III', name='clasificacion_riesgo'), nullable=True),
    sa.Column('estado', sa.Enum('operativo', 'mantenimiento', 'fuera_de_servicio', 'baja', name='estado_equipo'), server_default='operativo', nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=True),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('fecha_adquisicion', sa.Date(), nullable=True),
    sa.Column('costo_adquisicion', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('fin_garantia', sa.Date(), nullable=True),
    sa.Column('orden_compra', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], name=op.f('fk_equipos_proveedor_id_proveedores')),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], name=op.f('fk_equipos_sede_id_sedes')),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], name=op.f('fk_equipos_servicio_id_servicios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipos'))
    )
    op.create_index(op.f('ix_equipos_codigo_interno'), 'equipos', ['codigo_interno'], unique=True)
    op.create_index(op.f('ix_equipos_nombre'), 'equipos', ['nombre'], unique=False)
    op.create_index(op.f('ix_equipos_sede_id'), 'equipos', ['sede_id'], unique=False)
    op.create_index(op.f('ix_equipos_serial_fabricante'), 'equipos', ['serial_fabricante'], unique=False)
    op.create_index(op.f('ix_equipos_servicio_id'), 'equipos', ['servicio_id'], unique=False)
    op.create_table('movimientos_equipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('sede_origen_id', sa.Integer(), nullable=True),
    sa.Column('servicio_origen_id', sa.Integer(), nullable=True),
    sa.Column('sede_destino_id', sa.Integer(), nullable=True),
    sa.Column('servicio_destino_id', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.String(length=250), nullable=True),
    sa.Column('responsable', sa.String(length=150), nullable=True),
    sa.Column('fecha_movimiento', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], name=op.f('fk_movimientos_equipo_equipo_id_equipos')),
    sa.ForeignKeyConstraint(['sede_destino_id'], ['sedes.id'], name=op.f('fk_movimientos_equipo_sede_destino_id_sedes')),
    sa.ForeignKeyConstraint(['sede_origen_id'], ['sedes.id'], name=op.f('fk_movimientos_equipo_sede_origen_id_sedes')),
    sa.ForeignKeyConstraint(['servicio_destino_id'], ['servicios.id'], name=op.f('fk_movimientos_equipo_servicio_destino_id_servicios')),
    sa.ForeignKeyConstraint(['servicio_origen_id'], ['servicios.id'], name=op.f('fk_movimientos_equipo_servicio_origen_id_servicios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movimientos_equipo'))
    )
    op.create_index(op.f('ix_movimientos_equipo_equipo_id'), 'movimientos_equipo', ['equipo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimientos_equipo_equipo_id'), table_name='movimientos_equipo')
    op.drop_table('movimientos_equipo')
    op.drop_index(op.f('ix_equipos_servicio_id'), table_name='equipos')
    op.drop_index(op.f('ix_equipos_serial_fabricante'), table_name='equipos')
    op.drop_index(op.f('ix_equipos_sede_id'), table_name='equipos')
    op.drop_index(op.f('ix_equipos_nombre'), table_name='equipos')
    op.drop_index(op.f('ix_equipos_codigo_interno'), table_name='equipos')
    op.drop_table('equipos')
    op.drop_index(op.f('ix_servicios_sede_id'), table_name='servicios')
    op.drop_index(op.f('ix_servicios_nombre'), table_name='servicios')
    op.drop_table('servicios')
    op.drop_index(op.f('ix_sedes_nombre'), table_name='sedes')
    op.drop_table('sedes')
    op.drop_index(op.f('ix_proveedores_nombre'), table_name='proveedores')
    op.drop_table('proveedores')
    # ### end Alembic commands ###
