"""modulos y acceso por rol

Revision ID: df83e5d14dd3
Revises: 1e89e68f7c20
Create Date: 2026-09-03 10:06:05.454903
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df83e5d14dd3'
down_revision: str | None = '1e89e68f7c20'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('icono', sa.String(length=16), nullable=True),
    sa.Column('orden', sa.Integer(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_modulos'))
    )
    op.create_index(op.f('ix_modulos_slug'), 'modulos', ['slug'], unique=True)
    op.create_table('rol_modulo',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulos.id'], name=op.f('fk_rol_modulo_modulo_id_modulos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], name=op.f('fk_rol_modulo_rol_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rol_id', 'modulo_id', name=op.f('pk_rol_modulo'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rol_modulo')
    op.drop_index(op.f('ix_modulos_slug'), table_name='modulos')
    op.drop_table('modulos')
    # ### end Alembic commands ###
