"""add ordenes_trabajo y checklists (RF-013)

Revision ID: fdf2bce648a6
Revises: 45b8a4e0f22f
Create Date: 2026-09-07 16:25:43.890885
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fdf2bce648a6'
down_revision: str | None = '45b8a4e0f22f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklists_equipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], name=op.f('fk_checklists_equipo_equipo_id_equipos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checklists_equipo'))
    )
    op.create_index(op.f('ix_checklists_equipo_equipo_id'), 'checklists_equipo', ['equipo_id'], unique=True)
    op.create_table('ordenes_trabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('preventivo', 'correctivo', 'calibracion', name='tipo_mantenimiento'), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'en_progreso', 'completada', 'cancelada', name='estado_ot'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.Column('fecha_programada', sa.DateTime(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.Column('tiempo_empleado_minutos', sa.Integer(), nullable=True),
    sa.Column('costo_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('firma_coordinador', sa.Text(), nullable=True),
    sa.Column('firma_tecnico', sa.Text(), nullable=True),
    sa.Column('fecha_firma_coordinador', sa.DateTime(), nullable=True),
    sa.Column('fecha_firma_tecnico', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], name=op.f('fk_ordenes_trabajo_equipo_id_equipos')),
    sa.ForeignKeyConstraint(['tecnico_id'], ['usuarios.id'], name=op.f('fk_ordenes_trabajo_tecnico_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ordenes_trabajo'))
    )
    op.create_index(op.f('ix_ordenes_trabajo_equipo_id'), 'ordenes_trabajo', ['equipo_id'], unique=False)
    op.create_table('checklist_pasos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('instrucciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists_equipo.id'], name=op.f('fk_checklist_pasos_checklist_id_checklists_equipo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checklist_pasos'))
    )
    op.create_index(op.f('ix_checklist_pasos_checklist_id'), 'checklist_pasos', ['checklist_id'], unique=False)
    op.create_table('ejecucion_checklist_pasos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ot_id', sa.Integer(), nullable=False),
    sa.Column('paso_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('R', 'NR', 'PA', name='estado_checklist'), nullable=False),
    sa.Column('observacion', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['ot_id'], ['ordenes_trabajo.id'], name=op.f('fk_ejecucion_checklist_pasos_ot_id_ordenes_trabajo')),
    sa.ForeignKeyConstraint(['paso_id'], ['checklist_pasos.id'], name=op.f('fk_ejecucion_checklist_pasos_paso_id_checklist_pasos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ejecucion_checklist_pasos'))
    )
    op.create_index(op.f('ix_ejecucion_checklist_pasos_ot_id'), 'ejecucion_checklist_pasos', ['ot_id'], unique=False)
    op.alter_column('documento_equipos', 'tipo',
               existing_type=sa.VARCHAR(length=30),
               comment='manual | plano | calibracion | recomendacion',
               existing_nullable=False)
    op.alter_column('documento_equipos', 'ruta_archivo',
               existing_type=sa.VARCHAR(length=500),
               comment='Ruta relativa en el servidor: uploads/documentos/equipo_{id}/{tipo}/{nombre}',
               existing_nullable=False)
    op.alter_column('documento_equipos', 'tamaño_bytes',
               existing_type=sa.INTEGER(),
               comment='Tamaño en bytes del archivo',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documento_equipos', 'tamaño_bytes',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Tamaño en bytes del archivo',
               existing_nullable=False)
    op.alter_column('documento_equipos', 'ruta_archivo',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Ruta relativa en el servidor: uploads/documentos/equipo_{id}/{tipo}/{nombre}',
               existing_nullable=False)
    op.alter_column('documento_equipos', 'tipo',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='manual | plano | calibracion | recomendacion',
               existing_nullable=False)
    op.create_table('Schedule',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('departmentId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('scheduleType', sa.VARCHAR(), server_default=sa.text("'FIXED'::character varying"), autoincrement=False, nullable=False),
    sa.Column('daysOfWeek', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('toleranceMin', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('expectedEntriesPerDay', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expectedExitsPerDay', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('isActive', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('isDeleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('deletedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['departmentId'], ['Department.id'], name=op.f('fk_Schedule_departmentId_Department')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Schedule'))
    )
    op.create_table('attendance_app_settings',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_app_settings')),
    sa.UniqueConstraint('key', name=op.f('uq_attendance_app_settings_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('Department',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('isActive', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('isDeleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('deletedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Department')),
    sa.UniqueConstraint('name', name=op.f('uq_Department_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_Department_name'), 'Department', ['name'], unique=True)
    op.create_table('processing_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('original_file_name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('total_rows', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_entries', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_exits', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_late_arrivals', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_without_late', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_inconsistencies', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_early_leaves', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_record_count_issues', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('report_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_history'))
    )
    op.create_table('attendance_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('processing_history_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('legajo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('department_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('record_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('record_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('record_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('day_of_week', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('classification', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('late_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('early_leave_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_inconsistency', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('observation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['processing_history_id'], ['processing_history.id'], name=op.f('fk_attendance_records_processing_history_id_processing_history'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_records'))
    )
    op.create_index(op.f('ix_attendance_records_record_date'), 'attendance_records', ['record_date'], unique=False)
    op.create_index(op.f('ix_attendance_records_processing_history_id'), 'attendance_records', ['processing_history_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_legajo'), 'attendance_records', ['legajo'], unique=False)
    op.create_index(op.f('ix_attendance_records_department_name'), 'attendance_records', ['department_name'], unique=False)
    op.create_index(op.f('ix_attendance_records_department_id'), 'attendance_records', ['department_id'], unique=False)
    op.create_table('ProcessingHistory',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('originalFileName', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('processedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('totalRows', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('totalEntries', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('totalExits', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('totalLateArrivals', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('totalWithoutLate', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('totalInconsistencies', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('totalEarlyLeaves', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('totalRecordCountIssues', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('reportPath', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('errorMessage', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ProcessingHistory'))
    )
    op.create_table('schedules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('schedule_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('days_of_week', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tolerance_min', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expected_entries_per_day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expected_exits_per_day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_schedules_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedules'))
    )
    op.create_index(op.f('ix_schedules_department_id'), 'schedules', ['department_id'], unique=False)
    op.create_table('AttendanceRecord',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('processingHistoryId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('legajo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('departmentId', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('departmentName', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('recordType', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('recordDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('recordDateTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('dayOfWeek', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('classification', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('lateMinutes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('earlyLeaveMinutes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('isInconsistency', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['processingHistoryId'], ['ProcessingHistory.id'], name=op.f('fk_AttendanceRecord_processingHistoryId_ProcessingHistory'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_AttendanceRecord'))
    )
    op.create_table('app_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_settings'))
    )
    op.create_index(op.f('ix_app_settings_key'), 'app_settings', ['key'], unique=True)
    op.create_table('departments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments'))
    )
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_table('ScheduleBlock',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('scheduleId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('startTime', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('endTime', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('blockOrder', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('crossesMidnight', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('isEntryPoint', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['scheduleId'], ['Schedule.id'], name=op.f('fk_ScheduleBlock_scheduleId_Schedule'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ScheduleBlock'))
    )
    op.create_table('schedule_blocks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('start_time', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('end_time', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('block_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('crosses_midnight', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_entry_point', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name=op.f('fk_schedule_blocks_schedule_id_schedules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_blocks'))
    )
    op.create_index(op.f('ix_schedule_blocks_schedule_id'), 'schedule_blocks', ['schedule_id'], unique=False)
    op.drop_index(op.f('ix_ejecucion_checklist_pasos_ot_id'), table_name='ejecucion_checklist_pasos')
    op.drop_table('ejecucion_checklist_pasos')
    op.drop_index(op.f('ix_checklist_pasos_checklist_id'), table_name='checklist_pasos')
    op.drop_table('checklist_pasos')
    op.drop_index(op.f('ix_ordenes_trabajo_equipo_id'), table_name='ordenes_trabajo')
    op.drop_table('ordenes_trabajo')
    op.drop_index(op.f('ix_checklists_equipo_equipo_id'), table_name='checklists_equipo')
    op.drop_table('checklists_equipo')
    # ### end Alembic commands ###
