"""Puerto del repositorio de equipos (RF-001..007)."""
from typing import Protocol

from app.application.dto.equipos import FiltroEquipos
from app.domain.entities.equipo import Equipo


class EquipoRepository(Protocol):
    def listar(self, filtro: FiltroEquipos) -> list[Equipo]: ...

    def obtener_por_id(self, equipo_id: int) -> Equipo | None: ...

    def existe_codigo(self, codigo: str, excluir_id: int | None = None) -> bool: ...

    def siguiente_codigo(self) -> str: ...

    def crear(self, equipo: Equipo) -> Equipo: ...

    def actualizar(self, equipo_id: int, datos: Equipo) -> Equipo: ...

    def eliminar(self, equipo_id: int) -> None: ...
