"""Puerto del repositorio de proveedores (RF-005)."""
from typing import Protocol

from app.domain.entities.proveedor import Proveedor


class ProveedorRepository(Protocol):
    def listar(self) -> list[Proveedor]: ...

    def obtener_por_id(self, proveedor_id: int) -> Proveedor | None: ...

    def existe_nombre(self, nombre: str, excluir_id: int | None = None) -> bool: ...

    def crear(self, proveedor: Proveedor) -> Proveedor: ...

    def actualizar(self, proveedor_id: int, datos: Proveedor) -> Proveedor: ...

    def eliminar(self, proveedor_id: int) -> None: ...

    def contar_equipos(self, proveedor_id: int) -> int: ...
