"""Puerto del repositorio de roles (RF-028, RF-029)."""
from typing import Protocol

from app.domain.entities.rol import Rol


class RolRepository(Protocol):
    def listar(self) -> list[Rol]: ...

    def obtener_por_id(self, rol_id: int) -> Rol | None: ...

    def obtener_por_nombre(self, nombre: str) -> Rol | None: ...

    def existe_nombre(self, nombre: str) -> bool: ...

    def crear(self, nombre: str, descripcion: str | None, permiso_ids: list[int]) -> Rol: ...

    def actualizar(
        self, rol_id: int, nombre: str, descripcion: str | None
    ) -> Rol: ...

    def establecer_permisos(self, rol_id: int, permiso_ids: list[int]) -> Rol: ...

    def eliminar(self, rol_id: int) -> None: ...

    def contar_usuarios(self, rol_id: int) -> int: ...
